# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := MyEngine
DEFS_Default :=

# Flags passed to all source files.
CFLAGS_Default := \
	-Wall \
	-Wextra \
	-pedantic \
	-std=c++11

# Flags passed to only C files.
CFLAGS_C_Default :=

# Flags passed to only C++ files.
CFLAGS_CC_Default :=

INCS_Default := \
	-Iinclude

OBJS := \
	$(obj).target/$(TARGET)/src/AmbientLight.o \
	$(obj).target/$(TARGET)/src/Animation.o \
	$(obj).target/$(TARGET)/src/AnimationHandler.o \
	$(obj).target/$(TARGET)/src/AnimationMorphTarget.o \
	$(obj).target/$(TARGET)/src/AreaLight.o \
	$(obj).target/$(TARGET)/src/Bone.o \
	$(obj).target/$(TARGET)/src/Box3.o \
	$(obj).target/$(TARGET)/src/Camera.o \
	$(obj).target/$(TARGET)/src/Color.o \
	$(obj).target/$(TARGET)/src/CompressedTexture.o \
	$(obj).target/$(TARGET)/src/Curve.o \
	$(obj).target/$(TARGET)/src/CurvePath.o \
	$(obj).target/$(TARGET)/src/DataTexture.o \
	$(obj).target/$(TARGET)/src/DirctionalLight.o \
	$(obj).target/$(TARGET)/src/Euler.o \
	$(obj).target/$(TARGET)/src/Face3.o \
	$(obj).target/$(TARGET)/src/Fog.o \
	$(obj).target/$(TARGET)/src/FoxExp2.o \
	$(obj).target/$(TARGET)/src/Geometry.o \
	$(obj).target/$(TARGET)/src/GLES2Renderer.o \
	$(obj).target/$(TARGET)/src/Gyroscope.o \
	$(obj).target/$(TARGET)/src/HemisphereLight.o \
	$(obj).target/$(TARGET)/src/KeyFrameAnimation.o \
	$(obj).target/$(TARGET)/src/Light.o \
	$(obj).target/$(TARGET)/src/Line.o \
	$(obj).target/$(TARGET)/src/Loader.o \
	$(obj).target/$(TARGET)/src/LOD.o \
	$(obj).target/$(TARGET)/src/Material.o \
	$(obj).target/$(TARGET)/src/Matrix3.o \
	$(obj).target/$(TARGET)/src/Matrix4.o \
	$(obj).target/$(TARGET)/src/Mesh.o \
	$(obj).target/$(TARGET)/src/MorphAnimMesh.o \
	$(obj).target/$(TARGET)/src/Object3D.o \
	$(obj).target/$(TARGET)/src/OpenGLRenderer.o \
	$(obj).target/$(TARGET)/src/OrthographicCamera.o \
	$(obj).target/$(TARGET)/src/Path.o \
	$(obj).target/$(TARGET)/src/PerspectiveCamera.o \
	$(obj).target/$(TARGET)/src/Plane.o \
	$(obj).target/$(TARGET)/src/PointCloud.o \
	$(obj).target/$(TARGET)/src/PointLight.o \
	$(obj).target/$(TARGET)/src/Quanternion.o \
	$(obj).target/$(TARGET)/src/Ray.o \
	$(obj).target/$(TARGET)/src/RayTraceRenderer.o \
	$(obj).target/$(TARGET)/src/Renderer.o \
	$(obj).target/$(TARGET)/src/Scene.o \
	$(obj).target/$(TARGET)/src/Shape.o \
	$(obj).target/$(TARGET)/src/SkinnedMesh.o \
	$(obj).target/$(TARGET)/src/Sphere.o \
	$(obj).target/$(TARGET)/src/Spline.o \
	$(obj).target/$(TARGET)/src/SpotLight.o \
	$(obj).target/$(TARGET)/src/Sprite.o \
	$(obj).target/$(TARGET)/src/Texture.o \
	$(obj).target/$(TARGET)/src/Triangle.o \
	$(obj).target/$(TARGET)/src/Vector2.o \
	$(obj).target/$(TARGET)/src/Vector3.o \
	$(obj).target/$(TARGET)/src/Vector4.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Default :=

LIBS :=

$(builddir)/MyEngine: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(builddir)/MyEngine: LIBS := $(LIBS)
$(builddir)/MyEngine: LD_INPUTS := $(OBJS)
$(builddir)/MyEngine: TOOLSET := $(TOOLSET)
$(builddir)/MyEngine: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,link)

all_deps += $(builddir)/MyEngine
# Add target alias
.PHONY: MyEngine
MyEngine: $(builddir)/MyEngine

# Add executable to "all" target.
.PHONY: all
all: $(builddir)/MyEngine

