#ifndef MYUPLAY_MYENGINE_SHADERCHUNK
#define MYUPLAY_MYENGINE_SHADERCHUNK
#include <string>

namespace MyUPlay {
namespace MyEngine {
namespace ShaderChunk {
const std::string alphamap_fragment =
"#ifdef USE_ALPHAMAP\n"
"\n"
"diffuseColor.a *= texture2D( alphaMap, vUv ).g;\n"
"\n"
"#endif\n";
const std::string alphamap_pars_fragment =
"#ifdef USE_ALPHAMAP\n"
"\n"
"uniform sampler2D alphaMap;\n"
"\n"
"#endif\n";
const std::string alphatest_fragment =
"#ifdef ALPHATEST\n"
"\n"
"if ( diffuseColor.a < ALPHATEST ) discard;\n"
"\n"
"#endif\n";
const std::string aomap_fragment =
"#ifdef USE_AOMAP\n"
"\n"
"totalAmbientLight *= ( texture2D( aoMap, vUv2 ).r - 1.0 ) * aoMapIntensity + 1.0;\n"
"\n"
"#endif\n";
const std::string aomap_pars_fragment =
"#ifdef USE_AOMAP\n"
"\n"
"uniform sampler2D aoMap;\n"
"uniform float aoMapIntensity;\n"
"\n"
"#endif\n";
const std::string beginnormal_vertex =
"\n"
"vec3 objectNormal = vec3( normal );\n";
const std::string begin_vertex =
"\n"
"vec3 transformed = vec3( position );\n";
const std::string bumpmap_pars_fragment =
"#ifdef USE_BUMPMAP\n"
"\n"
"uniform sampler2D bumpMap;\n"
"uniform float bumpScale;\n"
"\n"
"// Derivative maps - bump mapping unparametrized surfaces by Morten Mikkelsen\n"
"// http://mmikkelsen3d.blogspot.sk/2011/07/derivative-maps.html\n"
"\n"
"// Evaluate the derivative of the height w.r.t. screen-space using forward differencing (listing 2)\n"
"\n"
"vec2 dHdxy_fwd() {\n"
"\n"
"vec2 dSTdx = dFdx( vUv );\n"
"vec2 dSTdy = dFdy( vUv );\n"
"\n"
"float Hll = bumpScale * texture2D( bumpMap, vUv ).x;\n"
"float dBx = bumpScale * texture2D( bumpMap, vUv + dSTdx ).x - Hll;\n"
"float dBy = bumpScale * texture2D( bumpMap, vUv + dSTdy ).x - Hll;\n"
"\n"
"return vec2( dBx, dBy );\n"
"\n"
"}\n"
"\n"
"vec3 perturbNormalArb( vec3 surf_pos, vec3 surf_norm, vec2 dHdxy ) {\n"
"\n"
"vec3 vSigmaX = dFdx( surf_pos );\n"
"vec3 vSigmaY = dFdy( surf_pos );\n"
"vec3 vN = surf_norm;		// normalized\n"
"\n"
"vec3 R1 = cross( vSigmaY, vN );\n"
"vec3 R2 = cross( vN, vSigmaX );\n"
"\n"
"float fDet = dot( vSigmaX, R1 );\n"
"\n"
"vec3 vGrad = sign( fDet ) * ( dHdxy.x * R1 + dHdxy.y * R2 );\n"
"return normalize( abs( fDet ) * surf_norm - vGrad );\n"
"\n"
"}\n"
"\n"
"#endif\n";
const std::string color_fragment =
"#ifdef USE_COLOR\n"
"\n"
"diffuseColor.rgb *= vColor;\n"
"\n"
"#endif\n";
const std::string color_pars_fragment =
"#ifdef USE_COLOR\n"
"\n"
"varying vec3 vColor;\n"
"\n"
"#endif\n";
const std::string color_pars_vertex =
"#ifdef USE_COLOR\n"
"\n"
"varying vec3 vColor;\n"
"\n"
"#endif\n";
const std::string color_vertex =
"#ifdef USE_COLOR\n"
"\n"
"vColor.xyz = color.xyz;\n"
"\n"
"#endif\n";
const std::string common =
"#define PI 3.14159\n"
"#define PI2 6.28318\n"
"#define RECIPROCAL_PI2 0.15915494\n"
"#define LOG2 1.442695\n"
"#define EPSILON 1e-6\n"
"\n"
"#define saturate(a) clamp( a, 0.0, 1.0 )\n"
"#define whiteCompliment(a) ( 1.0 - saturate( a ) )\n"
"\n"
"vec3 transformDirection( in vec3 normal, in mat4 matrix ) {\n"
"\n"
"return normalize( ( matrix * vec4( normal, 0.0 ) ).xyz );\n"
"\n"
"}\n"
"\n"
"// http://en.wikibooks.org/wiki/GLSL_Programming/Applying_Matrix_Transformations\n"
"vec3 inverseTransformDirection( in vec3 normal, in mat4 matrix ) {\n"
"\n"
"return normalize( ( vec4( normal, 0.0 ) * matrix ).xyz );\n"
"\n"
"}\n"
"\n"
"vec3 projectOnPlane(in vec3 point, in vec3 pointOnPlane, in vec3 planeNormal ) {\n"
"\n"
"float distance = dot( planeNormal, point - pointOnPlane );\n"
"\n"
"return - distance * planeNormal + point;\n"
"\n"
"}\n"
"\n"
"float sideOfPlane( in vec3 point, in vec3 pointOnPlane, in vec3 planeNormal ) {\n"
"\n"
"return sign( dot( point - pointOnPlane, planeNormal ) );\n"
"\n"
"}\n"
"\n"
"vec3 linePlaneIntersect( in vec3 pointOnLine, in vec3 lineDirection, in vec3 pointOnPlane, in vec3 planeNormal ) {\n"
"\n"
"return lineDirection * ( dot( planeNormal, pointOnPlane - pointOnLine ) / dot( planeNormal, lineDirection ) ) + pointOnLine;\n"
"\n"
"}\n"
"\n"
"float calcLightAttenuation( float lightDistance, float cutoffDistance, float decayExponent ) {\n"
"\n"
"if ( decayExponent > 0.0 ) {\n"
"\n"
"return pow( saturate( -lightDistance / cutoffDistance + 1.0 ), decayExponent );\n"
"\n"
"}\n"
"\n"
"return 1.0;\n"
"\n"
"}\n"
"\n"
"vec3 F_Schlick( in vec3 specularColor, in float dotLH ) {\n"
"\n"
"// Original approximation by Christophe Schlick '94\n"
"//;float fresnel = pow( 1.0 - dotLH, 5.0 );\n"
"\n"
"// Optimized variant (presented by Epic at SIGGRAPH '13)\n"
"float fresnel = exp2( ( -5.55437 * dotLH - 6.98316 ) * dotLH );\n"
"\n"
"return ( 1.0 - specularColor ) * fresnel + specularColor;\n"
"\n"
"}\n"
"\n"
"float G_BlinnPhong_Implicit( /* in float dotNL, in float dotNV */ ) {\n"
"\n"
"// geometry term is (n⋅l)(n⋅v) / 4(n⋅l)(n⋅v)\n"
"\n"
"return 0.25;\n"
"\n"
"}\n"
"\n"
"float D_BlinnPhong( in float shininess, in float dotNH ) {\n"
"\n"
"// factor of 1/PI in distribution term omitted\n"
"\n"
"return ( shininess * 0.5 + 1.0 ) * pow( dotNH, shininess );\n"
"\n"
"}\n"
"\n"
"vec3 BRDF_BlinnPhong( in vec3 specularColor, in float shininess, in vec3 normal, in vec3 lightDir, in vec3 viewDir ) {\n"
"\n"
"vec3 halfDir = normalize( lightDir + viewDir );\n"
"\n"
"//float dotNL = saturate( dot( normal, lightDir ) );\n"
"//float dotNV = saturate( dot( normal, viewDir ) );\n"
"float dotNH = saturate( dot( normal, halfDir ) );\n"
"float dotLH = saturate( dot( lightDir, halfDir ) );\n"
"\n"
"vec3 F = F_Schlick( specularColor, dotLH );\n"
"\n"
"float G = G_BlinnPhong_Implicit( /* dotNL, dotNV */ );\n"
"\n"
"float D = D_BlinnPhong( shininess, dotNH );\n"
"\n"
"return F * G * D;\n"
"\n"
"}\n"
"\n"
"vec3 inputToLinear( in vec3 a ) {\n"
"\n"
"#ifdef GAMMA_INPUT\n"
"\n"
"return pow( a, vec3( float( GAMMA_FACTOR ) ) );\n"
"\n"
"#else\n"
"\n"
"return a;\n"
"\n"
"#endif\n"
"\n"
"}\n"
"\n"
"vec3 linearToOutput( in vec3 a ) {\n"
"\n"
"#ifdef GAMMA_OUTPUT\n"
"\n"
"return pow( a, vec3( 1.0 / float( GAMMA_FACTOR ) ) );\n"
"\n"
"#else\n"
"\n"
"return a;\n"
"\n"
"#endif\n"
"\n"
"}\n";
const std::string defaultnormal_vertex =
"#ifdef FLIP_SIDED\n"
"\n"
"objectNormal = -objectNormal;\n"
"\n"
"#endif\n"
"\n"
"vec3 transformedNormal = normalMatrix * objectNormal;\n";
const std::string displacementmap_pars_vertex =
"#ifdef USE_DISPLACEMENTMAP\n"
"\n"
"uniform sampler2D displacementMap;\n"
"uniform float displacementScale;\n"
"uniform float displacementBias;\n"
"\n"
"#endif\n";
const std::string displacementmap_vertex =
"#ifdef USE_DISPLACEMENTMAP\n"
"\n"
"transformed += normal * ( texture2D( displacementMap, uv ).x * displacementScale + displacementBias );\n"
"\n"
"#endif\n";
const std::string emissivemap_fragment =
"#ifdef USE_EMISSIVEMAP\n"
"\n"
"vec4 emissiveColor = texture2D( emissiveMap, vUv );\n"
"\n"
"emissiveColor.rgb = inputToLinear( emissiveColor.rgb );\n"
"\n"
"totalEmissiveLight *= emissiveColor.rgb;\n"
"\n"
"#endif\n";
const std::string emissivemap_pars_fragment =
"#ifdef USE_EMISSIVEMAP\n"
"\n"
"uniform sampler2D emissiveMap;\n"
"\n"
"#endif\n";
const std::string envmap_fragment =
"#ifdef USE_ENVMAP\n"
"\n"
"#if defined( USE_BUMPMAP ) || defined( USE_NORMALMAP ) || defined( PHONG )\n"
"\n"
"vec3 cameraToVertex = normalize( vWorldPosition - cameraPosition );\n"
"\n"
"// Transforming Normal Vectors with the Inverse Transformation\n"
"vec3 worldNormal = inverseTransformDirection( normal, viewMatrix );\n"
"\n"
"#ifdef ENVMAP_MODE_REFLECTION\n"
"\n"
"vec3 reflectVec = reflect( cameraToVertex, worldNormal );\n"
"\n"
"#else\n"
"\n"
"vec3 reflectVec = refract( cameraToVertex, worldNormal, refractionRatio );\n"
"\n"
"#endif\n"
"\n"
"#else\n"
"\n"
"vec3 reflectVec = vReflect;\n"
"\n"
"#endif\n"
"\n"
"#ifdef DOUBLE_SIDED\n"
"float flipNormal = ( float( gl_FrontFacing ) * 2.0 - 1.0 );\n"
"#else\n"
"float flipNormal = 1.0;\n"
"#endif\n"
"\n"
"#ifdef ENVMAP_TYPE_CUBE\n"
"vec4 envColor = textureCube( envMap, flipNormal * vec3( flipEnvMap * reflectVec.x, reflectVec.yz ) );\n"
"\n"
"#elif defined( ENVMAP_TYPE_EQUIREC )\n"
"vec2 sampleUV;\n"
"sampleUV.y = saturate( flipNormal * reflectVec.y * 0.5 + 0.5 );\n"
"sampleUV.x = atan( flipNormal * reflectVec.z, flipNormal * reflectVec.x ) * RECIPROCAL_PI2 + 0.5;\n"
"vec4 envColor = texture2D( envMap, sampleUV );\n"
"\n"
"#elif defined( ENVMAP_TYPE_SPHERE )\n"
"vec3 reflectView = flipNormal * normalize((viewMatrix * vec4( reflectVec, 0.0 )).xyz + vec3(0.0,0.0,1.0));\n"
"vec4 envColor = texture2D( envMap, reflectView.xy * 0.5 + 0.5 );\n"
"#endif\n"
"\n"
"envColor.xyz = inputToLinear( envColor.xyz );\n"
"\n"
"#ifdef ENVMAP_BLENDING_MULTIPLY\n"
"\n"
"outgoingLight = mix( outgoingLight, outgoingLight * envColor.xyz, specularStrength * reflectivity );\n"
"\n"
"#elif defined( ENVMAP_BLENDING_MIX )\n"
"\n"
"outgoingLight = mix( outgoingLight, envColor.xyz, specularStrength * reflectivity );\n"
"\n"
"#elif defined( ENVMAP_BLENDING_ADD )\n"
"\n"
"outgoingLight += envColor.xyz * specularStrength * reflectivity;\n"
"\n"
"#endif\n"
"\n"
"#endif\n";
const std::string envmap_pars_fragment =
"#ifdef USE_ENVMAP\n"
"\n"
"uniform float reflectivity;\n"
"#ifdef ENVMAP_TYPE_CUBE\n"
"uniform samplerCube envMap;\n"
"#else\n"
"uniform sampler2D envMap;\n"
"#endif\n"
"uniform float flipEnvMap;\n"
"\n"
"#if defined( USE_BUMPMAP ) || defined( USE_NORMALMAP ) || defined( PHONG )\n"
"\n"
"uniform float refractionRatio;\n"
"\n"
"#else\n"
"\n"
"varying vec3 vReflect;\n"
"\n"
"#endif\n"
"\n"
"#endif\n";
const std::string envmap_pars_vertex =
"#if defined( USE_ENVMAP ) && ! defined( USE_BUMPMAP ) && ! defined( USE_NORMALMAP ) && ! defined( PHONG )\n"
"\n"
"varying vec3 vReflect;\n"
"\n"
"uniform float refractionRatio;\n"
"\n"
"#endif\n";
const std::string envmap_vertex =
"#if defined( USE_ENVMAP ) && ! defined( USE_BUMPMAP ) && ! defined( USE_NORMALMAP ) && ! defined( PHONG )\n"
"\n"
"vec3 cameraToVertex = normalize( worldPosition.xyz - cameraPosition );\n"
"\n"
"vec3 worldNormal = inverseTransformDirection( transformedNormal, viewMatrix );\n"
"\n"
"#ifdef ENVMAP_MODE_REFLECTION\n"
"\n"
"vReflect = reflect( cameraToVertex, worldNormal );\n"
"\n"
"#else\n"
"\n"
"vReflect = refract( cameraToVertex, worldNormal, refractionRatio );\n"
"\n"
"#endif\n"
"\n"
"#endif\n";
const std::string fog_fragment =
"#ifdef USE_FOG\n"
"\n"
"#ifdef USE_LOGDEPTHBUF_EXT\n"
"\n"
"float depth = gl_FragDepthEXT / gl_FragCoord.w;\n"
"\n"
"#else\n"
"\n"
"float depth = gl_FragCoord.z / gl_FragCoord.w;\n"
"\n"
"#endif\n"
"\n"
"#ifdef FOG_EXP2\n"
"\n"
"float fogFactor = whiteCompliment( exp2( - fogDensity * fogDensity * depth * depth * LOG2 ) );\n"
"\n"
"#else\n"
"\n"
"float fogFactor = smoothstep( fogNear, fogFar, depth );\n"
"\n"
"#endif\n"
"\n"
"outgoingLight = mix( outgoingLight, fogColor, fogFactor );\n"
"\n"
"#endif\n";
const std::string fog_pars_fragment =
"#ifdef USE_FOG\n"
"\n"
"uniform vec3 fogColor;\n"
"\n"
"#ifdef FOG_EXP2\n"
"\n"
"uniform float fogDensity;\n"
"\n"
"#else\n"
"\n"
"uniform float fogNear;\n"
"uniform float fogFar;\n"
"#endif\n"
"\n"
"#endif\n";
const std::string hemilight_fragment =
"#if MAX_HEMI_LIGHTS > 0\n"
"\n"
"for ( int i = 0; i < MAX_HEMI_LIGHTS; i ++ ) {\n"
"\n"
"vec3 lightDir = hemisphereLightDirection[ i ];\n"
"\n"
"float dotProduct = dot( normal, lightDir );\n"
"\n"
"float hemiDiffuseWeight = 0.5 * dotProduct + 0.5;\n"
"\n"
"vec3 lightColor = mix( hemisphereLightGroundColor[ i ], hemisphereLightSkyColor[ i ], hemiDiffuseWeight );\n"
"\n"
"totalAmbientLight += lightColor;\n"
"\n"
"}\n"
"\n"
"#endif\n"
"\n";
const std::string lightmap_fragment =
"#ifdef USE_LIGHTMAP\n"
"\n"
"totalAmbientLight += texture2D( lightMap, vUv2 ).xyz * lightMapIntensity;\n"
"\n"
"#endif\n";
const std::string lightmap_pars_fragment =
"#ifdef USE_LIGHTMAP\n"
"\n"
"uniform sampler2D lightMap;\n"
"uniform float lightMapIntensity;\n"
"\n"
"#endif\n";
const std::string lights_lambert_pars_vertex =
"#if MAX_DIR_LIGHTS > 0\n"
"\n"
"uniform vec3 directionalLightColor[ MAX_DIR_LIGHTS ];\n"
"uniform vec3 directionalLightDirection[ MAX_DIR_LIGHTS ];\n"
"\n"
"#endif\n"
"\n"
"#if MAX_HEMI_LIGHTS > 0\n"
"\n"
"uniform vec3 hemisphereLightSkyColor[ MAX_HEMI_LIGHTS ];\n"
"uniform vec3 hemisphereLightGroundColor[ MAX_HEMI_LIGHTS ];\n"
"uniform vec3 hemisphereLightDirection[ MAX_HEMI_LIGHTS ];\n"
"\n"
"#endif\n"
"\n"
"#if MAX_POINT_LIGHTS > 0\n"
"\n"
"uniform vec3 pointLightColor[ MAX_POINT_LIGHTS ];\n"
"uniform vec3 pointLightPosition[ MAX_POINT_LIGHTS ];\n"
"uniform float pointLightDistance[ MAX_POINT_LIGHTS ];\n"
"uniform float pointLightDecay[ MAX_POINT_LIGHTS ];\n"
"\n"
"#endif\n"
"\n"
"#if MAX_SPOT_LIGHTS > 0\n"
"\n"
"uniform vec3 spotLightColor[ MAX_SPOT_LIGHTS ];\n"
"uniform vec3 spotLightPosition[ MAX_SPOT_LIGHTS ];\n"
"uniform vec3 spotLightDirection[ MAX_SPOT_LIGHTS ];\n"
"uniform float spotLightDistance[ MAX_SPOT_LIGHTS ];\n"
"uniform float spotLightAngleCos[ MAX_SPOT_LIGHTS ];\n"
"uniform float spotLightExponent[ MAX_SPOT_LIGHTS ];\n"
"uniform float spotLightDecay[ MAX_SPOT_LIGHTS ];\n"
"\n"
"#endif\n";
const std::string lights_lambert_vertex =
"vLightFront = vec3( 0.0 );\n"
"\n"
"#ifdef DOUBLE_SIDED\n"
"\n"
"vLightBack = vec3( 0.0 );\n"
"\n"
"#endif\n"
"\n"
"vec3 normal = normalize( transformedNormal );\n"
"\n"
"#if MAX_POINT_LIGHTS > 0\n"
"\n"
"for ( int i = 0; i < MAX_POINT_LIGHTS; i ++ ) {\n"
"\n"
"vec3 lightColor = pointLightColor[ i ];\n"
"\n"
"vec3 lVector = pointLightPosition[ i ] - mvPosition.xyz;\n"
"vec3 lightDir = normalize( lVector );\n"
"\n"
"// attenuation\n"
"\n"
"float attenuation = calcLightAttenuation( length( lVector ), pointLightDistance[ i ], pointLightDecay[ i ] );\n"
"\n"
"// diffuse\n"
"\n"
"float dotProduct = dot( normal, lightDir );\n"
"\n"
"vLightFront += lightColor * attenuation * saturate( dotProduct );\n"
"\n"
"#ifdef DOUBLE_SIDED\n"
"\n"
"vLightBack += lightColor * attenuation * saturate( - dotProduct );\n"
"\n"
"#endif\n"
"\n"
"}\n"
"\n"
"#endif\n"
"\n"
"#if MAX_SPOT_LIGHTS > 0\n"
"\n"
"for ( int i = 0; i < MAX_SPOT_LIGHTS; i ++ ) {\n"
"\n"
"vec3 lightColor = spotLightColor[ i ];\n"
"\n"
"vec3 lightPosition = spotLightPosition[ i ];\n"
"vec3 lVector = lightPosition - mvPosition.xyz;\n"
"vec3 lightDir = normalize( lVector );\n"
"\n"
"float spotEffect = dot( spotLightDirection[ i ], lightDir );\n"
"\n"
"if ( spotEffect > spotLightAngleCos[ i ] ) {\n"
"\n"
"spotEffect = saturate( pow( saturate( spotEffect ), spotLightExponent[ i ] ) );\n"
"\n"
"// attenuation\n"
"\n"
"float attenuation = calcLightAttenuation( length( lVector ), spotLightDistance[ i ], spotLightDecay[ i ] );\n"
"\n"
"attenuation *= spotEffect;\n"
"\n"
"// diffuse\n"
"\n"
"float dotProduct = dot( normal, lightDir );\n"
"\n"
"vLightFront += lightColor * attenuation * saturate( dotProduct );\n"
"\n"
"#ifdef DOUBLE_SIDED\n"
"\n"
"vLightBack += lightColor * attenuation * saturate( - dotProduct );\n"
"\n"
"#endif\n"
"\n"
"}\n"
"\n"
"}\n"
"\n"
"#endif\n"
"\n"
"#if MAX_DIR_LIGHTS > 0\n"
"\n"
"for ( int i = 0; i < MAX_DIR_LIGHTS; i ++ ) {\n"
"\n"
"vec3 lightColor = directionalLightColor[ i ];\n"
"\n"
"vec3 lightDir = directionalLightDirection[ i ];\n"
"\n"
"// diffuse\n"
"\n"
"float dotProduct = dot( normal, lightDir );\n"
"\n"
"vLightFront += lightColor * saturate( dotProduct );\n"
"\n"
"#ifdef DOUBLE_SIDED\n"
"\n"
"vLightBack += lightColor * saturate( - dotProduct );\n"
"\n"
"#endif\n"
"\n"
"}\n"
"\n"
"#endif\n"
"\n"
"#if MAX_HEMI_LIGHTS > 0\n"
"\n"
"for ( int i = 0; i < MAX_HEMI_LIGHTS; i ++ ) {\n"
"\n"
"vec3 lightDir = hemisphereLightDirection[ i ];\n"
"\n"
"// diffuse\n"
"\n"
"float dotProduct = dot( normal, lightDir );\n"
"\n"
"float hemiDiffuseWeight = 0.5 * dotProduct + 0.5;\n"
"\n"
"vLightFront += mix( hemisphereLightGroundColor[ i ], hemisphereLightSkyColor[ i ], hemiDiffuseWeight );\n"
"\n"
"#ifdef DOUBLE_SIDED\n"
"\n"
"float hemiDiffuseWeightBack = - 0.5 * dotProduct + 0.5;\n"
"\n"
"vLightBack += mix( hemisphereLightGroundColor[ i ], hemisphereLightSkyColor[ i ], hemiDiffuseWeightBack );\n"
"\n"
"#endif\n"
"\n"
"}\n"
"\n"
"#endif\n";
const std::string lights_phong_fragment =
"vec3 viewDir = normalize( vViewPosition );\n"
"\n"
"vec3 totalDiffuseLight = vec3( 0.0 );\n"
"vec3 totalSpecularLight = vec3( 0.0 );\n"
"\n"
"#if MAX_POINT_LIGHTS > 0\n"
"\n"
"for ( int i = 0; i < MAX_POINT_LIGHTS; i ++ ) {\n"
"\n"
"vec3 lightColor = pointLightColor[ i ];\n"
"\n"
"vec3 lightPosition = pointLightPosition[ i ];\n"
"vec3 lVector = lightPosition + vViewPosition.xyz;\n"
"vec3 lightDir = normalize( lVector );\n"
"\n"
"// attenuation\n"
"\n"
"float attenuation = calcLightAttenuation( length( lVector ), pointLightDistance[ i ], pointLightDecay[ i ] );\n"
"\n"
"// diffuse\n"
"\n"
"float cosineTerm = saturate( dot( normal, lightDir ) );\n"
"\n"
"totalDiffuseLight += lightColor * attenuation * cosineTerm;\n"
"\n"
"// specular\n"
"\n"
"vec3 brdf = BRDF_BlinnPhong( specular, shininess, normal, lightDir, viewDir );\n"
"\n"
"totalSpecularLight += brdf * specularStrength * lightColor * attenuation * cosineTerm;\n"
"\n"
"\n"
"}\n"
"\n"
"#endif\n"
"\n"
"#if MAX_SPOT_LIGHTS > 0\n"
"\n"
"for ( int i = 0; i < MAX_SPOT_LIGHTS; i ++ ) {\n"
"\n"
"vec3 lightColor = spotLightColor[ i ];\n"
"\n"
"vec3 lightPosition = spotLightPosition[ i ];\n"
"vec3 lVector = lightPosition + vViewPosition.xyz;\n"
"vec3 lightDir = normalize( lVector );\n"
"\n"
"float spotEffect = dot( spotLightDirection[ i ], lightDir );\n"
"\n"
"if ( spotEffect > spotLightAngleCos[ i ] ) {\n"
"\n"
"spotEffect = saturate( pow( saturate( spotEffect ), spotLightExponent[ i ] ) );\n"
"\n"
"// attenuation\n"
"\n"
"float attenuation = calcLightAttenuation( length( lVector ), spotLightDistance[ i ], spotLightDecay[ i ] );\n"
"\n"
"attenuation *= spotEffect;\n"
"\n"
"// diffuse\n"
"\n"
"float cosineTerm = saturate( dot( normal, lightDir ) );\n"
"\n"
"totalDiffuseLight += lightColor * attenuation * cosineTerm;\n"
"\n"
"// specular\n"
"\n"
"vec3 brdf = BRDF_BlinnPhong( specular, shininess, normal, lightDir, viewDir );\n"
"\n"
"totalSpecularLight += brdf * specularStrength * lightColor * attenuation * cosineTerm;\n"
"\n"
"}\n"
"\n"
"}\n"
"\n"
"#endif\n"
"\n"
"#if MAX_DIR_LIGHTS > 0\n"
"\n"
"for ( int i = 0; i < MAX_DIR_LIGHTS; i ++ ) {\n"
"\n"
"vec3 lightColor = directionalLightColor[ i ];\n"
"\n"
"vec3 lightDir = directionalLightDirection[ i ];\n"
"\n"
"// diffuse\n"
"\n"
"float cosineTerm = saturate( dot( normal, lightDir ) );\n"
"\n"
"totalDiffuseLight += lightColor * cosineTerm;\n"
"\n"
"// specular\n"
"\n"
"vec3 brdf = BRDF_BlinnPhong( specular, shininess, normal, lightDir, viewDir );\n"
"\n"
"totalSpecularLight += brdf * specularStrength * lightColor * cosineTerm;\n"
"\n"
"}\n"
"\n"
"#endif\n";
const std::string lights_phong_pars_fragment =
"uniform vec3 ambientLightColor;\n"
"\n"
"#if MAX_DIR_LIGHTS > 0\n"
"\n"
"uniform vec3 directionalLightColor[ MAX_DIR_LIGHTS ];\n"
"uniform vec3 directionalLightDirection[ MAX_DIR_LIGHTS ];\n"
"\n"
"#endif\n"
"\n"
"#if MAX_HEMI_LIGHTS > 0\n"
"\n"
"uniform vec3 hemisphereLightSkyColor[ MAX_HEMI_LIGHTS ];\n"
"uniform vec3 hemisphereLightGroundColor[ MAX_HEMI_LIGHTS ];\n"
"uniform vec3 hemisphereLightDirection[ MAX_HEMI_LIGHTS ];\n"
"\n"
"#endif\n"
"\n"
"#if MAX_POINT_LIGHTS > 0\n"
"\n"
"uniform vec3 pointLightColor[ MAX_POINT_LIGHTS ];\n"
"\n"
"uniform vec3 pointLightPosition[ MAX_POINT_LIGHTS ];\n"
"uniform float pointLightDistance[ MAX_POINT_LIGHTS ];\n"
"uniform float pointLightDecay[ MAX_POINT_LIGHTS ];\n"
"\n"
"#endif\n"
"\n"
"#if MAX_SPOT_LIGHTS > 0\n"
"\n"
"uniform vec3 spotLightColor[ MAX_SPOT_LIGHTS ];\n"
"uniform vec3 spotLightPosition[ MAX_SPOT_LIGHTS ];\n"
"uniform vec3 spotLightDirection[ MAX_SPOT_LIGHTS ];\n"
"uniform float spotLightAngleCos[ MAX_SPOT_LIGHTS ];\n"
"uniform float spotLightExponent[ MAX_SPOT_LIGHTS ];\n"
"uniform float spotLightDistance[ MAX_SPOT_LIGHTS ];\n"
"uniform float spotLightDecay[ MAX_SPOT_LIGHTS ];\n"
"\n"
"#endif\n"
"\n"
"#if MAX_SPOT_LIGHTS > 0 || defined( USE_ENVMAP )\n"
"\n"
"varying vec3 vWorldPosition;\n"
"\n"
"#endif\n"
"\n"
"varying vec3 vViewPosition;\n"
"\n"
"#ifndef FLAT_SHADED\n"
"\n"
"varying vec3 vNormal;\n"
"\n"
"#endif\n";
const std::string lights_phong_pars_vertex =
"#if MAX_SPOT_LIGHTS > 0 || defined( USE_ENVMAP )\n"
"\n"
"varying vec3 vWorldPosition;\n"
"\n"
"#endif\n"
"\n"
"#if MAX_POINT_LIGHTS > 0\n"
"\n"
"uniform vec3 pointLightPosition[ MAX_POINT_LIGHTS ];\n"
"\n"
"#endif\n";
const std::string lights_phong_vertex =
"#if MAX_SPOT_LIGHTS > 0 || defined( USE_ENVMAP )\n"
"\n"
"vWorldPosition = worldPosition.xyz;\n"
"\n"
"#endif\n";
const std::string linear_to_gamma_fragment =
"\n"
"outgoingLight = linearToOutput( outgoingLight );\n";
const std::string logdepthbuf_fragment =
"#if defined(USE_LOGDEPTHBUF) && defined(USE_LOGDEPTHBUF_EXT)\n"
"\n"
"gl_FragDepthEXT = log2(vFragDepth) * logDepthBufFC * 0.5;\n"
"\n"
"#endif\n";
const std::string logdepthbuf_pars_fragment =
"#ifdef USE_LOGDEPTHBUF\n"
"\n"
"uniform float logDepthBufFC;\n"
"\n"
"#ifdef USE_LOGDEPTHBUF_EXT\n"
"\n"
"varying float vFragDepth;\n"
"\n"
"#endif\n"
"\n"
"#endif\n";
const std::string logdepthbuf_pars_vertex =
"#ifdef USE_LOGDEPTHBUF\n"
"\n"
"#ifdef USE_LOGDEPTHBUF_EXT\n"
"\n"
"varying float vFragDepth;\n"
"\n"
"#endif\n"
"\n"
"uniform float logDepthBufFC;\n"
"\n"
"#endif\n";
const std::string logdepthbuf_vertex =
"#ifdef USE_LOGDEPTHBUF\n"
"\n"
"gl_Position.z = log2(max( EPSILON, gl_Position.w + 1.0 )) * logDepthBufFC;\n"
"\n"
"#ifdef USE_LOGDEPTHBUF_EXT\n"
"\n"
"vFragDepth = 1.0 + gl_Position.w;\n"
"\n"
"#else\n"
"\n"
"gl_Position.z = (gl_Position.z - 1.0) * gl_Position.w;\n"
"\n"
"#endif\n"
"\n"
"#endif\n";
const std::string map_fragment =
"#ifdef USE_MAP\n"
"\n"
"vec4 texelColor = texture2D( map, vUv );\n"
"\n"
"texelColor.xyz = inputToLinear( texelColor.xyz );\n"
"\n"
"diffuseColor *= texelColor;\n"
"\n"
"#endif\n";
const std::string map_pars_fragment =
"#ifdef USE_MAP\n"
"\n"
"uniform sampler2D map;\n"
"\n"
"#endif\n";
const std::string map_particle_fragment =
"#ifdef USE_MAP\n"
"\n"
"diffuseColor *= texture2D( map, vec2( gl_PointCoord.x, 1.0 - gl_PointCoord.y ) * offsetRepeat.zw + offsetRepeat.xy );\n"
"\n"
"#endif\n";
const std::string map_particle_pars_fragment =
"#ifdef USE_MAP\n"
"\n"
"uniform vec4 offsetRepeat;\n"
"uniform sampler2D map;\n"
"\n"
"#endif\n";
const std::string morphnormal_vertex =
"#ifdef USE_MORPHNORMALS\n"
"\n"
"objectNormal += ( morphNormal0 - normal ) * morphTargetInfluences[ 0 ];\n"
"objectNormal += ( morphNormal1 - normal ) * morphTargetInfluences[ 1 ];\n"
"objectNormal += ( morphNormal2 - normal ) * morphTargetInfluences[ 2 ];\n"
"objectNormal += ( morphNormal3 - normal ) * morphTargetInfluences[ 3 ];\n"
"\n"
"#endif\n";
const std::string morphtarget_pars_vertex =
"#ifdef USE_MORPHTARGETS\n"
"\n"
"#ifndef USE_MORPHNORMALS\n"
"\n"
"uniform float morphTargetInfluences[ 8 ];\n"
"\n"
"#else\n"
"\n"
"uniform float morphTargetInfluences[ 4 ];\n"
"\n"
"#endif\n"
"\n"
"#endif\n";
const std::string morphtarget_vertex =
"#ifdef USE_MORPHTARGETS\n"
"\n"
"transformed += ( morphTarget0 - position ) * morphTargetInfluences[ 0 ];\n"
"transformed += ( morphTarget1 - position ) * morphTargetInfluences[ 1 ];\n"
"transformed += ( morphTarget2 - position ) * morphTargetInfluences[ 2 ];\n"
"transformed += ( morphTarget3 - position ) * morphTargetInfluences[ 3 ];\n"
"\n"
"#ifndef USE_MORPHNORMALS\n"
"\n"
"transformed += ( morphTarget4 - position ) * morphTargetInfluences[ 4 ];\n"
"transformed += ( morphTarget5 - position ) * morphTargetInfluences[ 5 ];\n"
"transformed += ( morphTarget6 - position ) * morphTargetInfluences[ 6 ];\n"
"transformed += ( morphTarget7 - position ) * morphTargetInfluences[ 7 ];\n"
"\n"
"#endif\n"
"\n"
"#endif\n";
const std::string normalmap_pars_fragment =
"#ifdef USE_NORMALMAP\n"
"\n"
"uniform sampler2D normalMap;\n"
"uniform vec2 normalScale;\n"
"\n"
"// Per-Pixel Tangent Space Normal Mapping\n"
"// http://hacksoflife.blogspot.ch/2009/11/per-pixel-tangent-space-normal-mapping.html\n"
"\n"
"vec3 perturbNormal2Arb( vec3 eye_pos, vec3 surf_norm ) {\n"
"\n"
"vec3 q0 = dFdx( eye_pos.xyz );\n"
"vec3 q1 = dFdy( eye_pos.xyz );\n"
"vec2 st0 = dFdx( vUv.st );\n"
"vec2 st1 = dFdy( vUv.st );\n"
"\n"
"vec3 S = normalize( q0 * st1.t - q1 * st0.t );\n"
"vec3 T = normalize( -q0 * st1.s + q1 * st0.s );\n"
"vec3 N = normalize( surf_norm );\n"
"\n"
"vec3 mapN = texture2D( normalMap, vUv ).xyz * 2.0 - 1.0;\n"
"mapN.xy = normalScale * mapN.xy;\n"
"mat3 tsn = mat3( S, T, N );\n"
"return normalize( tsn * mapN );\n"
"\n"
"}\n"
"\n"
"#endif\n";
const std::string normal_phong_fragment =
"#ifndef FLAT_SHADED\n"
"\n"
"vec3 normal = normalize( vNormal );\n"
"\n"
"#ifdef DOUBLE_SIDED\n"
"\n"
"normal = normal * ( -1.0 + 2.0 * float( gl_FrontFacing ) );\n"
"\n"
"#endif\n"
"\n"
"#else\n"
"\n"
"vec3 fdx = dFdx( vViewPosition );\n"
"vec3 fdy = dFdy( vViewPosition );\n"
"vec3 normal = normalize( cross( fdx, fdy ) );\n"
"\n"
"#endif\n"
"\n"
"#ifdef USE_NORMALMAP\n"
"\n"
"normal = perturbNormal2Arb( -vViewPosition, normal );\n"
"\n"
"#elif defined( USE_BUMPMAP )\n"
"\n"
"normal = perturbNormalArb( -vViewPosition, normal, dHdxy_fwd() );\n"
"\n"
"#endif\n"
"\n";
const std::string project_vertex =
"#ifdef USE_SKINNING\n"
"\n"
"vec4 mvPosition = modelViewMatrix * skinned;\n"
"\n"
"#else\n"
"\n"
"vec4 mvPosition = modelViewMatrix * vec4( transformed, 1.0 );\n"
"\n"
"#endif\n"
"\n"
"gl_Position = projectionMatrix * mvPosition;\n";
const std::string shadowmap_fragment =
"#ifdef USE_SHADOWMAP\n"
"\n"
"for ( int i = 0; i < MAX_SHADOWS; i ++ ) {\n"
"\n"
"float texelSizeY =  1.0 / shadowMapSize[ i ].y;\n"
"\n"
"float shadow = 0.0;\n"
"\n"
"#if defined( POINT_LIGHT_SHADOWS )\n"
"\n"
"// to save on uniform space, we use the sign of @shadowDarkness[ i ] to determine\n"
"// whether or not this light is a point light ( shadowDarkness[ i ] < 0 == point light)\n"
"bool isPointLight = shadowDarkness[ i ] < 0.0;\n"
"\n"
"if ( isPointLight ) {\n"
"\n"
"// get the real shadow darkness\n"
"float realShadowDarkness = abs( shadowDarkness[ i ] );\n"
"\n"
"// for point lights, the uniform @vShadowCoord is re-purposed to hold\n"
"// the distance from the light to the world-space position of the fragment.\n"
"vec3 lightToPosition = vShadowCoord[ i ].xyz;\n"
"\n"
"#if defined( SHADOWMAP_TYPE_PCF ) || defined( SHADOWMAP_TYPE_PCF_SOFT )\n"
"\n"
"// bd3D = base direction 3D\n"
"vec3 bd3D = normalize( lightToPosition );\n"
"// dp = distance from light to fragment position\n"
"float dp = length( lightToPosition );\n"
"\n"
"// base measurement\n"
"adjustShadowValue1K( dp, texture2D( shadowMap[ i ], cubeToUV( bd3D, texelSizeY ) ), shadowBias[ i ], shadow );\n"
"\n"
"// Dr = disk radius\n"
"\n"
"#if defined( SHADOWMAP_TYPE_PCF )\n"
"const float Dr = 1.25;\n"
"#elif defined( SHADOWMAP_TYPE_PCF_SOFT )\n"
"const float Dr = 2.25;\n"
"#endif\n"
"\n"
"// os = offset scale\n"
"float os = Dr *  2.0 * texelSizeY;\n"
"\n"
"const vec3 Gsd = vec3( - 1, 0, 1 );\n"
"\n"
"adjustShadowValue1K( dp, texture2D( shadowMap[ i ], cubeToUV( bd3D + Gsd.zzz * os, texelSizeY ) ), shadowBias[ i ], shadow );\n"
"adjustShadowValue1K( dp, texture2D( shadowMap[ i ], cubeToUV( bd3D + Gsd.zxz * os, texelSizeY ) ), shadowBias[ i ], shadow );\n"
"adjustShadowValue1K( dp, texture2D( shadowMap[ i ], cubeToUV( bd3D + Gsd.xxz * os, texelSizeY ) ), shadowBias[ i ], shadow );\n"
"adjustShadowValue1K( dp, texture2D( shadowMap[ i ], cubeToUV( bd3D + Gsd.xzz * os, texelSizeY ) ), shadowBias[ i ], shadow );\n"
"adjustShadowValue1K( dp, texture2D( shadowMap[ i ], cubeToUV( bd3D + Gsd.zzx * os, texelSizeY ) ), shadowBias[ i ], shadow );\n"
"adjustShadowValue1K( dp, texture2D( shadowMap[ i ], cubeToUV( bd3D + Gsd.zxx * os, texelSizeY ) ), shadowBias[ i ], shadow );\n"
"adjustShadowValue1K( dp, texture2D( shadowMap[ i ], cubeToUV( bd3D + Gsd.xxx * os, texelSizeY ) ), shadowBias[ i ], shadow );\n"
"adjustShadowValue1K( dp, texture2D( shadowMap[ i ], cubeToUV( bd3D + Gsd.xzx * os, texelSizeY ) ), shadowBias[ i ], shadow );\n"
"adjustShadowValue1K( dp, texture2D( shadowMap[ i ], cubeToUV( bd3D + Gsd.zzy * os, texelSizeY ) ), shadowBias[ i ], shadow );\n"
"adjustShadowValue1K( dp, texture2D( shadowMap[ i ], cubeToUV( bd3D + Gsd.zxy * os, texelSizeY ) ), shadowBias[ i ], shadow );\n"
"\n"
"adjustShadowValue1K( dp, texture2D( shadowMap[ i ], cubeToUV( bd3D + Gsd.xxy * os, texelSizeY ) ), shadowBias[ i ], shadow );\n"
"adjustShadowValue1K( dp, texture2D( shadowMap[ i ], cubeToUV( bd3D + Gsd.xzy * os, texelSizeY ) ), shadowBias[ i ], shadow );\n"
"adjustShadowValue1K( dp, texture2D( shadowMap[ i ], cubeToUV( bd3D + Gsd.zyz * os, texelSizeY ) ), shadowBias[ i ], shadow );\n"
"adjustShadowValue1K( dp, texture2D( shadowMap[ i ], cubeToUV( bd3D + Gsd.xyz * os, texelSizeY ) ), shadowBias[ i ], shadow );\n"
"adjustShadowValue1K( dp, texture2D( shadowMap[ i ], cubeToUV( bd3D + Gsd.zyx * os, texelSizeY ) ), shadowBias[ i ], shadow );\n"
"adjustShadowValue1K( dp, texture2D( shadowMap[ i ], cubeToUV( bd3D + Gsd.xyx * os, texelSizeY ) ), shadowBias[ i ], shadow );\n"
"adjustShadowValue1K( dp, texture2D( shadowMap[ i ], cubeToUV( bd3D + Gsd.yzz * os, texelSizeY ) ), shadowBias[ i ], shadow );\n"
"adjustShadowValue1K( dp, texture2D( shadowMap[ i ], cubeToUV( bd3D + Gsd.yxz * os, texelSizeY ) ), shadowBias[ i ], shadow );\n"
"adjustShadowValue1K( dp, texture2D( shadowMap[ i ], cubeToUV( bd3D + Gsd.yxx * os, texelSizeY ) ), shadowBias[ i ], shadow );\n"
"adjustShadowValue1K( dp, texture2D( shadowMap[ i ], cubeToUV( bd3D + Gsd.yzx * os, texelSizeY ) ), shadowBias[ i ], shadow );\n"
"\n"
"shadow *= realShadowDarkness * ( 1.0 / 21.0 );\n"
"\n"
"#else // no percentage-closer filtering:\n"
"\n"
"vec3 bd3D = normalize( lightToPosition );\n"
"float dp = length( lightToPosition );\n"
"\n"
"adjustShadowValue1K( dp, texture2D( shadowMap[ i ], cubeToUV( bd3D, texelSizeY ) ), shadowBias[ i ], shadow );\n"
"\n"
"shadow *= realShadowDarkness;\n"
"\n"
"#endif\n"
"\n"
"} else {\n"
"\n"
"#endif // POINT_LIGHT_SHADOWS\n"
"\n"
"float texelSizeX =  1.0 / shadowMapSize[ i ].x;\n"
"\n"
"vec3 shadowCoord = vShadowCoord[ i ].xyz / vShadowCoord[ i ].w;\n"
"\n"
"// if ( something && something ) breaks ATI OpenGL shader compiler\n"
"// if ( all( something, something ) ) using this instead\n"
"\n"
"bvec4 inFrustumVec = bvec4 ( shadowCoord.x >= 0.0, shadowCoord.x <= 1.0, shadowCoord.y >= 0.0, shadowCoord.y <= 1.0 );\n"
"bool inFrustum = all( inFrustumVec );\n"
"\n"
"bvec2 frustumTestVec = bvec2( inFrustum, shadowCoord.z <= 1.0 );\n"
"\n"
"bool frustumTest = all( frustumTestVec );\n"
"\n"
"if ( frustumTest ) {\n"
"\n"
"#if defined( SHADOWMAP_TYPE_PCF )\n"
"\n"
"// Percentage-close filtering\n"
"// (9 pixel kernel)\n"
"// http://fabiensanglard.net/shadowmappingPCF/\n"
"\n"
"/*\n"
"// nested loops breaks shader compiler / validator on some ATI cards when using OpenGL\n"
"// must enroll loop manually\n"
"for ( float y = -1.25; y <= 1.25; y += 1.25 )\n"
"for ( float x = -1.25; x <= 1.25; x += 1.25 ) {\n"
"vec4 rgbaDepth = texture2D( shadowMap[ i ], vec2( x * xPixelOffset, y * yPixelOffset ) + shadowCoord.xy );\n"
"// doesn't seem to produce any noticeable visual difference compared to simple texture2D lookup\n"
"//vec4 rgbaDepth = texture2DProj( shadowMap[ i ], vec4( vShadowCoord[ i ].w * ( vec2( x * xPixelOffset, y * yPixelOffset ) + shadowCoord.xy ), 0.05, vShadowCoord[ i ].w ) );\n"
"float fDepth = unpackDepth( rgbaDepth );\n"
"if ( fDepth < shadowCoord.z )\n"
"shadow += 1.0;\n"
"}\n"
"shadow /= 9.0;\n"
"*/\n"
"\n"
"shadowCoord.z += shadowBias[ i ];\n"
"\n"
"const float ShadowDelta = 1.0 / 9.0;\n"
"\n"
"float xPixelOffset = texelSizeX;\n"
"float yPixelOffset = texelSizeY;\n"
"\n"
"float dx0 = - 1.25 * xPixelOffset;\n"
"float dy0 = - 1.25 * yPixelOffset;\n"
"float dx1 = 1.25 * xPixelOffset;\n"
"float dy1 = 1.25 * yPixelOffset;\n"
"\n"
"float fDepth = unpackDepth( texture2D( shadowMap[ i ], shadowCoord.xy + vec2( dx0, dy0 ) ) );\n"
"if ( fDepth < shadowCoord.z ) shadow += ShadowDelta;\n"
"\n"
"fDepth = unpackDepth( texture2D( shadowMap[ i ], shadowCoord.xy + vec2( 0.0, dy0 ) ) );\n"
"if ( fDepth < shadowCoord.z ) shadow += ShadowDelta;\n"
"\n"
"fDepth = unpackDepth( texture2D( shadowMap[ i ], shadowCoord.xy + vec2( dx1, dy0 ) ) );\n"
"if ( fDepth < shadowCoord.z ) shadow += ShadowDelta;\n"
"\n"
"fDepth = unpackDepth( texture2D( shadowMap[ i ], shadowCoord.xy + vec2( dx0, 0.0 ) ) );\n"
"if ( fDepth < shadowCoord.z ) shadow += ShadowDelta;\n"
"\n"
"fDepth = unpackDepth( texture2D( shadowMap[ i ], shadowCoord.xy ) );\n"
"if ( fDepth < shadowCoord.z ) shadow += ShadowDelta;\n"
"\n"
"fDepth = unpackDepth( texture2D( shadowMap[ i ], shadowCoord.xy + vec2( dx1, 0.0 ) ) );\n"
"if ( fDepth < shadowCoord.z ) shadow += ShadowDelta;\n"
"\n"
"fDepth = unpackDepth( texture2D( shadowMap[ i ], shadowCoord.xy + vec2( dx0, dy1 ) ) );\n"
"if ( fDepth < shadowCoord.z ) shadow += ShadowDelta;\n"
"\n"
"fDepth = unpackDepth( texture2D( shadowMap[ i ], shadowCoord.xy + vec2( 0.0, dy1 ) ) );\n"
"if ( fDepth < shadowCoord.z ) shadow += ShadowDelta;\n"
"\n"
"fDepth = unpackDepth( texture2D( shadowMap[ i ], shadowCoord.xy + vec2( dx1, dy1 ) ) );\n"
"if ( fDepth < shadowCoord.z ) shadow += ShadowDelta;\n"
"\n"
"shadow *= shadowDarkness[ i ];\n"
"\n"
"#elif defined( SHADOWMAP_TYPE_PCF_SOFT )\n"
"\n"
"// Percentage-close filtering\n"
"// (9 pixel kernel)\n"
"// http://fabiensanglard.net/shadowmappingPCF/\n"
"\n"
"shadowCoord.z += shadowBias[ i ];\n"
"\n"
"float xPixelOffset = texelSizeX;\n"
"float yPixelOffset = texelSizeY;\n"
"\n"
"float dx0 = - 1.0 * xPixelOffset;\n"
"float dy0 = - 1.0 * yPixelOffset;\n"
"float dx1 = 1.0 * xPixelOffset;\n"
"float dy1 = 1.0 * yPixelOffset;\n"
"\n"
"mat3 shadowKernel;\n"
"mat3 depthKernel;\n"
"\n"
"depthKernel[ 0 ][ 0 ] = unpackDepth( texture2D( shadowMap[ i ], shadowCoord.xy + vec2( dx0, dy0 ) ) );\n"
"depthKernel[ 0 ][ 1 ] = unpackDepth( texture2D( shadowMap[ i ], shadowCoord.xy + vec2( dx0, 0.0 ) ) );\n"
"depthKernel[ 0 ][ 2 ] = unpackDepth( texture2D( shadowMap[ i ], shadowCoord.xy + vec2( dx0, dy1 ) ) );\n"
"depthKernel[ 1 ][ 0 ] = unpackDepth( texture2D( shadowMap[ i ], shadowCoord.xy + vec2( 0.0, dy0 ) ) );\n"
"depthKernel[ 1 ][ 1 ] = unpackDepth( texture2D( shadowMap[ i ], shadowCoord.xy ) );\n"
"depthKernel[ 1 ][ 2 ] = unpackDepth( texture2D( shadowMap[ i ], shadowCoord.xy + vec2( 0.0, dy1 ) ) );\n"
"depthKernel[ 2 ][ 0 ] = unpackDepth( texture2D( shadowMap[ i ], shadowCoord.xy + vec2( dx1, dy0 ) ) );\n"
"depthKernel[ 2 ][ 1 ] = unpackDepth( texture2D( shadowMap[ i ], shadowCoord.xy + vec2( dx1, 0.0 ) ) );\n"
"depthKernel[ 2 ][ 2 ] = unpackDepth( texture2D( shadowMap[ i ], shadowCoord.xy + vec2( dx1, dy1 ) ) );\n"
"\n"
"vec3 shadowZ = vec3( shadowCoord.z );\n"
"shadowKernel[ 0 ] = vec3( lessThan( depthKernel[ 0 ], shadowZ ) );\n"
"shadowKernel[ 0 ] *= vec3( 0.25 );\n"
"\n"
"shadowKernel[ 1 ] = vec3( lessThan( depthKernel[ 1 ], shadowZ ) );\n"
"shadowKernel[ 1 ] *= vec3( 0.25 );\n"
"\n"
"shadowKernel[ 2 ] = vec3( lessThan( depthKernel[ 2 ], shadowZ ) );\n"
"shadowKernel[ 2 ] *= vec3( 0.25 );\n"
"\n"
"vec2 fractionalCoord = 1.0 - fract( shadowCoord.xy * shadowMapSize[ i ].xy );\n"
"\n"
"shadowKernel[ 0 ] = mix( shadowKernel[ 1 ], shadowKernel[ 0 ], fractionalCoord.x );\n"
"shadowKernel[ 1 ] = mix( shadowKernel[ 2 ], shadowKernel[ 1 ], fractionalCoord.x );\n"
"\n"
"vec4 shadowValues;\n"
"shadowValues.x = mix( shadowKernel[ 0 ][ 1 ], shadowKernel[ 0 ][ 0 ], fractionalCoord.y );\n"
"shadowValues.y = mix( shadowKernel[ 0 ][ 2 ], shadowKernel[ 0 ][ 1 ], fractionalCoord.y );\n"
"shadowValues.z = mix( shadowKernel[ 1 ][ 1 ], shadowKernel[ 1 ][ 0 ], fractionalCoord.y );\n"
"shadowValues.w = mix( shadowKernel[ 1 ][ 2 ], shadowKernel[ 1 ][ 1 ], fractionalCoord.y );\n"
"\n"
"shadow = dot( shadowValues, vec4( 1.0 ) ) * shadowDarkness[ i ];\n"
"\n"
"#else // no percentage-closer filtering:\n"
"\n"
"shadowCoord.z += shadowBias[ i ];\n"
"\n"
"vec4 rgbaDepth = texture2D( shadowMap[ i ], shadowCoord.xy );\n"
"float fDepth = unpackDepth( rgbaDepth );\n"
"\n"
"if ( fDepth < shadowCoord.z )\n"
"shadow = shadowDarkness[ i ];\n"
"\n"
"#endif\n"
"\n"
"}\n"
"\n"
"#ifdef SHADOWMAP_DEBUG\n"
"\n"
"if ( inFrustum ) {\n"
"\n"
"if ( i == 0 ) {\n"
"\n"
"outgoingLight *= vec3( 1.0, 0.5, 0.0 );\n"
"\n"
"} else if ( i == 1 ) {\n"
"\n"
"outgoingLight *= vec3( 0.0, 1.0, 0.8 );\n"
"\n"
"} else {\n"
"\n"
"outgoingLight *= vec3( 0.0, 0.5, 1.0 );\n"
"\n"
"}\n"
"\n"
"}\n"
"\n"
"#endif\n"
"\n"
"#if defined( POINT_LIGHT_SHADOWS )\n"
"\n"
"}\n"
"\n"
"#endif\n"
"\n"
"shadowMask = shadowMask * vec3( 1.0 - shadow );\n"
"\n"
"}\n"
"\n"
"#endif\n";
const std::string shadowmap_pars_fragment =
"#ifdef USE_SHADOWMAP\n"
"\n"
"uniform sampler2D shadowMap[ MAX_SHADOWS ];\n"
"uniform vec2 shadowMapSize[ MAX_SHADOWS ];\n"
"\n"
"uniform float shadowDarkness[ MAX_SHADOWS ];\n"
"uniform float shadowBias[ MAX_SHADOWS ];\n"
"\n"
"varying vec4 vShadowCoord[ MAX_SHADOWS ];\n"
"\n"
"float unpackDepth( const in vec4 rgba_depth ) {\n"
"\n"
"const vec4 bit_shift = vec4( 1.0 / ( 256.0 * 256.0 * 256.0 ), 1.0 / ( 256.0 * 256.0 ), 1.0 / 256.0, 1.0 );\n"
"float depth = dot( rgba_depth, bit_shift );\n"
"return depth;\n"
"\n"
"}\n"
"\n"
"#if defined(POINT_LIGHT_SHADOWS)\n"
"\n"
"// adjustShadowValue1K() upacks the depth value stored in @textureData, adds @bias to it, and then\n"
"// comapres the result with @testDepth. If @testDepth is larger than or equal to that result, then\n"
"// @shadowValue is incremented by 1.0.\n"
"\n"
"void adjustShadowValue1K( const float testDepth, const vec4 textureData, const float bias, inout float shadowValue ) {\n"
"\n"
"const vec4 bitSh = vec4( 1.0 / ( 256.0 * 256.0 * 256.0 ), 1.0 / ( 256.0 * 256.0 ), 1.0 / 256.0, 1.0 );\n"
"if ( testDepth >= dot( textureData, bitSh ) * 1000.0 + bias )\n"
"shadowValue += 1.0;\n"
"\n"
"}\n"
"\n"
"// cubeToUV() maps a 3D direction vector suitable for cube texture mapping to a 2D\n"
"// vector suitable for 2D texture mapping. This code uses the following layout for the\n"
"// 2D texture:\n"
"//\n"
"// xzXZ\n"
"//  y Y\n"
"//\n"
"// Y - Positive y direction\n"
"// y - Negative y direction\n"
"// X - Positive x direction\n"
"// x - Negative x direction\n"
"// Z - Positive z direction\n"
"// z - Negative z direction\n"
"//\n"
"// Source and test bed:\n"
"// https://gist.github.com/tschw/da10c43c467ce8afd0c4\n"
"\n"
"vec2 cubeToUV( vec3 v, float texelSizeY ) {\n"
"\n"
"// Number of texels to avoid at the edge of each square\n"
"\n"
"vec3 absV = abs( v );\n"
"\n"
"// Intersect unit cube\n"
"\n"
"float scaleToCube = 1.0 / max( absV.x, max( absV.y, absV.z ) );\n"
"absV *= scaleToCube;\n"
"\n"
"// Apply scale to avoid seams\n"
"\n"
"// two texels less per square (one texel will do for NEAREST)\n"
"v *= scaleToCube * ( 1.0 - 2.0 * texelSizeY );\n"
"\n"
"// Unwrap\n"
"\n"
"// space: -1 ... 1 range for each square\n"
"//\n"
"// #X##		dim    := ( 4 , 2 )\n"
"//  # #		center := ( 1 , 1 )\n"
"\n"
"vec2 planar = v.xy;\n"
"\n"
"float almostATexel = 1.5 * texelSizeY;\n"
"float almostOne = 1.0 - almostATexel;\n"
"\n"
"if ( absV.z >= almostOne ) {\n"
"\n"
"if ( v.z > 0.0 )\n"
"planar.x = 4.0 - v.x;\n"
"\n"
"} else if ( absV.x >= almostOne ) {\n"
"\n"
"float signX = sign( v.x );\n"
"planar.x = v.z * signX + 2.0 * signX;\n"
"\n"
"} else if ( absV.y >= almostOne ) {\n"
"\n"
"float signY = sign( v.y );\n"
"planar.x = v.x + 2.0 * signY + 2.0;\n"
"planar.y = v.z * signY - 2.0;\n"
"\n"
"}\n"
"\n"
"// Transform to UV space\n"
"\n"
"// scale := 0.5 / dim\n"
"// translate := ( center + 0.5 ) / dim\n"
"return vec2( 0.125, 0.25 ) * planar + vec2( 0.375, 0.75 );\n"
"\n"
"}\n"
"\n"
"#endif\n"
"\n"
"#endif\n";
const std::string shadowmap_pars_vertex =
"#ifdef USE_SHADOWMAP\n"
"\n"
"uniform float shadowDarkness[ MAX_SHADOWS ];\n"
"uniform mat4 shadowMatrix[ MAX_SHADOWS ];\n"
"varying vec4 vShadowCoord[ MAX_SHADOWS ];\n"
"\n"
"#endif\n";
const std::string shadowmap_vertex =
"#ifdef USE_SHADOWMAP\n"
"\n"
"for ( int i = 0; i < MAX_SHADOWS; i ++ ) {\n"
"\n"
"vShadowCoord[ i ] = shadowMatrix[ i ] * worldPosition;\n"
"\n"
"}\n"
"\n"
"#endif\n";
const std::string skinbase_vertex =
"#ifdef USE_SKINNING\n"
"\n"
"mat4 boneMatX = getBoneMatrix( skinIndex.x );\n"
"mat4 boneMatY = getBoneMatrix( skinIndex.y );\n"
"mat4 boneMatZ = getBoneMatrix( skinIndex.z );\n"
"mat4 boneMatW = getBoneMatrix( skinIndex.w );\n"
"\n"
"#endif\n";
const std::string skinning_pars_vertex =
"#ifdef USE_SKINNING\n"
"\n"
"uniform mat4 bindMatrix;\n"
"uniform mat4 bindMatrixInverse;\n"
"\n"
"#ifdef BONE_TEXTURE\n"
"\n"
"uniform sampler2D boneTexture;\n"
"uniform int boneTextureWidth;\n"
"uniform int boneTextureHeight;\n"
"\n"
"mat4 getBoneMatrix( const in float i ) {\n"
"\n"
"float j = i * 4.0;\n"
"float x = mod( j, float( boneTextureWidth ) );\n"
"float y = floor( j / float( boneTextureWidth ) );\n"
"\n"
"float dx = 1.0 / float( boneTextureWidth );\n"
"float dy = 1.0 / float( boneTextureHeight );\n"
"\n"
"y = dy * ( y + 0.5 );\n"
"\n"
"vec4 v1 = texture2D( boneTexture, vec2( dx * ( x + 0.5 ), y ) );\n"
"vec4 v2 = texture2D( boneTexture, vec2( dx * ( x + 1.5 ), y ) );\n"
"vec4 v3 = texture2D( boneTexture, vec2( dx * ( x + 2.5 ), y ) );\n"
"vec4 v4 = texture2D( boneTexture, vec2( dx * ( x + 3.5 ), y ) );\n"
"\n"
"mat4 bone = mat4( v1, v2, v3, v4 );\n"
"\n"
"return bone;\n"
"\n"
"}\n"
"\n"
"#else\n"
"\n"
"uniform mat4 boneGlobalMatrices[ MAX_BONES ];\n"
"\n"
"mat4 getBoneMatrix( const in float i ) {\n"
"\n"
"mat4 bone = boneGlobalMatrices[ int(i) ];\n"
"return bone;\n"
"\n"
"}\n"
"\n"
"#endif\n"
"\n"
"#endif\n";
const std::string skinning_vertex =
"#ifdef USE_SKINNING\n"
"\n"
"vec4 skinVertex = bindMatrix * vec4( transformed, 1.0 );\n"
"\n"
"vec4 skinned = vec4( 0.0 );\n"
"skinned += boneMatX * skinVertex * skinWeight.x;\n"
"skinned += boneMatY * skinVertex * skinWeight.y;\n"
"skinned += boneMatZ * skinVertex * skinWeight.z;\n"
"skinned += boneMatW * skinVertex * skinWeight.w;\n"
"skinned  = bindMatrixInverse * skinned;\n"
"\n"
"#endif\n";
const std::string skinnormal_vertex =
"#ifdef USE_SKINNING\n"
"\n"
"mat4 skinMatrix = mat4( 0.0 );\n"
"skinMatrix += skinWeight.x * boneMatX;\n"
"skinMatrix += skinWeight.y * boneMatY;\n"
"skinMatrix += skinWeight.z * boneMatZ;\n"
"skinMatrix += skinWeight.w * boneMatW;\n"
"skinMatrix  = bindMatrixInverse * skinMatrix * bindMatrix;\n"
"\n"
"objectNormal = vec4( skinMatrix * vec4( objectNormal, 0.0 ) ).xyz;\n"
"\n"
"#endif\n";
const std::string specularmap_fragment =
"float specularStrength;\n"
"\n"
"#ifdef USE_SPECULARMAP\n"
"\n"
"vec4 texelSpecular = texture2D( specularMap, vUv );\n"
"specularStrength = texelSpecular.r;\n"
"\n"
"#else\n"
"\n"
"specularStrength = 1.0;\n"
"\n"
"#endif\n";
const std::string specularmap_pars_fragment =
"#ifdef USE_SPECULARMAP\n"
"\n"
"uniform sampler2D specularMap;\n"
"\n"
"#endif\n";
const std::string uv2_pars_fragment =
"#if defined( USE_LIGHTMAP ) || defined( USE_AOMAP )\n"
"\n"
"varying vec2 vUv2;\n"
"\n"
"#endif\n";
const std::string uv2_pars_vertex =
"#if defined( USE_LIGHTMAP ) || defined( USE_AOMAP )\n"
"\n"
"attribute vec2 uv2;\n"
"varying vec2 vUv2;\n"
"\n"
"#endif\n";
const std::string uv2_vertex =
"#if defined( USE_LIGHTMAP ) || defined( USE_AOMAP )\n"
"\n"
"vUv2 = uv2;\n"
"\n"
"#endif\n";
const std::string uv_pars_fragment =
"#if defined( USE_MAP ) || defined( USE_BUMPMAP ) || defined( USE_NORMALMAP ) || defined( USE_SPECULARMAP ) || defined( USE_ALPHAMAP ) || defined( USE_EMISSIVEMAP )\n"
"\n"
"varying vec2 vUv;\n"
"\n"
"#endif\n";
const std::string uv_pars_vertex =
"#if defined( USE_MAP ) || defined( USE_BUMPMAP ) || defined( USE_NORMALMAP ) || defined( USE_SPECULARMAP ) || defined( USE_ALPHAMAP ) || defined( USE_EMISSIVEMAP )\n"
"\n"
"varying vec2 vUv;\n"
"uniform vec4 offsetRepeat;\n"
"\n"
"#endif\n";
const std::string uv_vertex =
"#if defined( USE_MAP ) || defined( USE_BUMPMAP ) || defined( USE_NORMALMAP ) || defined( USE_SPECULARMAP ) || defined( USE_ALPHAMAP ) || defined( USE_EMISSIVEMAP )\n"
"\n"
"vUv = uv * offsetRepeat.zw + offsetRepeat.xy;\n"
"\n"
"#endif\n";
const std::string worldpos_vertex =
"#if defined( USE_ENVMAP ) || defined( PHONG ) || defined( LAMBERT ) || defined ( USE_SHADOWMAP )\n"
"\n"
"#ifdef USE_SKINNING\n"
"\n"
"vec4 worldPosition = modelMatrix * skinned;\n"
"\n"
"#else\n"
"\n"
"vec4 worldPosition = modelMatrix * vec4( transformed, 1.0 );\n"
"\n"
"#endif\n"
"\n"
"#endif\n";
}}}
#endif
